### ISSUE TITLE
Right clicking on an activated sign doesn't teleport you.

### ISSUE THREAD

**Issue by martin-danhier** [giuliojiang/Spigot-MultiWorldSignPortals#1]
Hey, nice plugin idea, this will be great if you want a creative world and a survival world on the same server, for example.
However, I installed it and I followed the instructions, but when I right click on the sign, I am not teleported. I only have the message "teleporting you to the world [redstone]"

Maybe this doesn't work with bukkit ?

**Comment by giuliojiang** [comment]
Hi, I can try to help if you give me a bit more info.

Do you have MultiWorld installed on the server?
If you run command `/goto redstone` do you get teleported? If this command doesn't work, your `redstone` world is not configured correctly.

**Comment by martin-danhier** [comment]
Ah, so you need a core plugin, I didn't know. Is it compatible with 1.13 ? Thank you for your answer.

**Comment by giuliojiang** [comment]
Yes, https://www.spigotmc.org/resources/multiworld.4598/

Fully developed on 1.13 only, so yes it's 1.13-compatible ;)

**Comment by martin-danhier** [comment]
Thank you, I'll check that out. :)

**Comment by martin-danhier** [comment]
It works well, now, thank you :)
